name: Publish Charm

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  publish-charm:
    name: Publish Charm to edge
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check libraries
        uses: canonical/charming-actions/check-libraries@1.0.0
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Upload charm to charmhub
        # TODO: update the upload-charm step once the following PR merges:
        # https://github.com/canonical/charming-actions/pull/33
        uses: claudiubelu/charming-actions/upload-charm@fix-upload-image-false-plus-perm
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          upload-image: "false"
          channel: "edge"
